### ISSUE TITLE
kube-lego deployed on GKE uses both NGINX and GLBC ingress controllers 

### ISSUE THREAD

**Issue by mstrzele** [jetstack/kube-lego#12]
When the `kube-lego` ingress is created, it uses both `nginx-ingress-controller` and `loadbalancer-controller`:

```
Name:                   kube-lego
Namespace:              default
Address:                5.6.7.8,1.2.3.4
Default backend:        default-http-backend:80 (10.84.0.3:8080)
Rules:
  Host                  Path    Backends
  ----                  ----    --------
  echo.example.com
                        /.well-known/acme-challenge     kube-lego:8080 (<none>)
Annotations:
  backends:             {"k8s-be-31590--64893abc10ca8449":"HEALTHY"}
  forwarding-rule:      k8s-fw-default-kube-lego--64893abc10ca8449
  ssl-redirect:         false
  target-proxy:         k8s-tp-default-kube-lego--64893abc10ca8449
  url-map:              k8s-um-default-kube-lego--64893abc10ca8449
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason  Message
  ---------     --------        -----   ----                            -------------   --------        ------  -------
  8m            8m              1       {nginx-ingress-controller }                     Normal          CREATE  default/kube-lego
  8m            8m              1       {loadbalancer-controller }                      Normal          ADD     default/kube-lego
  8m            7m              2       {nginx-ingress-controller }                     Normal          CREATE  ip: 1.2.3.4
  7m            7m              1       {loadbalancer-controller }                      Normal          CREATE  ip: 5.6.7.8
  7m            7m              1       {loadbalancer-controller }                      Warning         Status  Operation cannot be fulfilled on ingresses.extensions "kube-lego": the object has been modified; please apply your changes to the latest version and try again
  8m            2m              7       {nginx-ingress-controller }                     Normal          UPDATE  default/kube-lego
```

Probably it should be created with annotation [`kubernetes.io/ingress.class: "nginx"` to disable GLBC](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/BETA_LIMITATIONS.md#disabling-glbc).

**Comment by simonswine** [comment]
Plan to do that as part of #11. This annotations haven't been around for too long. Should happen within the next week :+1:

**Comment by MaxDaten** [comment]
What is about a simplification of the kube-lego setup?

One proposal:

- Use a `NodePort` for the `kube-lego` service. AFAIK `ports.type: NodePort` is already necessary of service ports receiving ingress traffic (atleast on GKE)?
- Manually (or automatically?) patch a referenced ingress resource (via env) to redirect `/.well-known/acme-challenge` to the `kube-lego` service.

I tried to change the configurations according to this, but the currently problem is, that `kube-lego` seems to stop after: 

```
time="2016-08-04T00:26:59Z" level=fatal msg="Error while process certificate requests: reachabily test failed for this cert" context=kubelego 
```

It restarts after a while, but not fast enough for the GKE health-check to recognize the service as healthy. So the ingress controller does not send any traffic to the service. Whats about to keep `kube-lego` up and running and always receiving traffic on `/` or `/healthz`?

**Comment by MaxDaten** [comment]
Okay got it working with GKE as a proof of concept.

My steps:

- `kube-lego-deployment.yaml`: Add a `livenessProbe`, so GKE can adopt this lifenessProbe for the health check for the backend-service
- `kube-lego-svc.yaml`: Set `ports.type: NodePort`
- `kube-lego-configmap.yaml`: Customize to your needs
- `kubectl apply -f kube-lego-configmap.yaml -f kube-lego-deployment.yaml -f kube-lego-svc.yaml`
- Change your ingress controller to redirect `/.well-known/acme-challenge/` to the `kube-lego` service. DO NOT set `annotations.kubernetes.io/tls-acme: "true"` in the ingress for now! (Reason: [1])
- Wait until the health check for `kube-lego` is HEALTHY (`watch kubectl describe ing`)
- Test manually if everything is redirected to your endpoints, especially to `kube-lego`: `curl -i http://example.com/.well-known/acme-challenge/_selftest` should be status 200.
- `kubectl annotate ing your-ingress-name kubernetes.io/tls-acme="true"` 
- Inspect the logs of the `kube-lego` pod and the secrets, hopefully it installed the desired secret and the GKE LoadBalancer installed it for SSL.

My examples as a Gist: https://gist.github.com/MaxDaten/482f6bd71348b1502edc7348318bea17

[1] You should not set `annotations.kubernetes.io/tls-acme: "true"` before health check for the backend-service is HEALTHY, because `kube-lego` immediately starts with the selfcheck, but no traffic on `/.well-known/acme-challenge` is redirected to it, as long the health check fails. This seems to result into a kind of deadlock.

**Comment by simonswine** [comment]
@MaxDaten thanks for your input on that. First of all I am not too sure if you are aware that there is a simple setup based on using nginx-ingress on GKE/GCE like this is:

- Disable L7-Loadbalancing in GKE: `gcloud container clusters update <cluster-name> --update-addons HttpLoadBalancing=DISABLED`
- Run nginx-ingress like described in the examples

I am using this for months without any issue. 

For having GCE ingress support, we need to support differentiation between ingress-classes. I plan to implement that for this ticket. This will include a lot of your (steps).

I agree on the deadlock, the reason for that is that kube-lego is currently not disabling ingress resources if they fail a couple of times, this is probably not trivial to implement. (see #13)

**Comment by MaxDaten** [comment]
> First of all I am not too sure if you are aware that there is a simple setup based on using nginx-ingress on GKE/GCE like this is:

Yes I'm aware of it, but wasn't aware how to disable the L7-LB, thanks for the hint. But this has the downside (depends on your perspective) to manage the LB on your own and you have to pull it into your cluster, since the L7 resides now on the managed master. Currently I prefer the managed LB. because I'm the one man army here.

**Comment by simonswine** [comment]
GCE should be supported as of release 0.1.0. Look at the [examples](/jetstack/kube-lego/tree/master/examples)

**Comment by MaxDaten** [comment]
Thanks alot, I will definitely try it out!

**Comment by MaxDaten** [comment]
Just stopping by to say thank you. I installed it, and it works like a charm =)
