### ISSUE TITLE
Support for Letsencrypt wildcard certificate

### ISSUE THREAD

**Issue by nagarjunac** [jetstack/kube-lego#318]
Hi, 

Letsencrypt has launched the support for wildcard certificate from january 4,2018  with a new v2 api end point. Help us to understand on how to create a single wild card certificate using kube lego.

**Comment by munnerz** [comment]
Hi there - Letsencrypt currently does not support ACMEv2 in production. A staging test endpoint was added on January 4th, with the production release cited for 27th Feb: https://letsencrypt.org/2017/06/14/acme-v2-api.html

As discussed in #304, we won't be adding support for this to kube-lego, not least because this project is now deprecated in favour of [cert-manager](https://github.com/jetstack/cert-manager), but also because wildcards are only available with DNS based validation, which kube-lego has never supported.

There is a PR on cert-manager to add support for wildcard certificates: https://github.com/jetstack/cert-manager/pull/309

Once the production endpoint is live, we will be merging that shortly afterwards.
