### ISSUE TITLE
AWS LoadBalancer Support

### ISSUE THREAD

**Issue by FrederikNS** [jetstack/kube-lego#41]
I would love a use this project for our Kubernetes cluster running in AWS. Unfortunately it doesn't seem that this project supports AWS ElasticLoadBalancers yet. I know that `lego` itself supports Route53 which is Amazons DNS provider, we just need the load balancer integration.

Whould this be possible to implement?

**Comment by carsonoid** [comment]
I run several clusters using kube-lego and ELBs without issue. Where are you getting tripped up?

**Comment by FrederikNS** [comment]
Oh cool!

I didn't try it out because I couldn't find any reference to AWS ELBs in the README, it only mentions GCE load balancers and nginx.

I also tried to dig through the issues, but still found no mention of AWS ELBs, but I'll definitely give it a try now, Thanks!

**Comment by carsonoid** [comment]
Glad to help! One thing that is good to know when using the [nginx ingress controller](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx) and ELBs is that you should enable ProxyProtocol for both the [controller ](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/proxy-protocol)and [ELB](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html) to allow the [whitelist](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/whitelist) annotations to work correctly. It will also make the ingress controller logs more useful since the real source IP will be shown.
